### ISSUE TITLE
Pre-compiled binaries

### ISSUE THREAD

**Issue by dfalbel** [Laurae2/lgbdl#7]
I have recently set up a project that provides pre-built binaries for LighGBM here: https://github.com/curso-r/lightgbm-build

Wondering if there's interest in providing something like:

```
lgbdl::lgb.dl(pre_built = TRUE)
```

To download and install from the pre-built binaries instead of compiling from source.

**Comment by Laurae2** [comment]
@dfalbel lgbdl package will be removed soon due to https://github.com/microsoft/LightGBM/pull/3035

However, in the new package (likely `lgbdl2`) it might be a good idea for the `pre_built` parameter but maybe in the form of something like `like_cran`: there are R users who compile themselves R and would be unable to use them.

**Comment by dfalbel** [comment]
OK! that makes sense! Let me know, I can work on a PR for the future `lgbdl2` adding this argument whenever it's ready for it.
